language: node_js
node_js:
- '0.10'
- '0.11'
before_script:
- rm -rf coverage/
script:
- npm run-script test-on-travis
deploy:
  api_key:
    secure: gF5wbQIGtpNA16oenbO8uKEzhHR5ztTQ9kEURSg2MUDA/TyI37sljvoETUkSgykdEjZOv8CquD5n09JkXEyvini0Mp4Xt6w62chIK7easjWDcrONIGuv9Ig3oJNf4PrIRkm8SoKA79AXPwxgIMebAlra571xHlQIWMky4dDiOEg=
  email: antoon.johansson@gmail.com
  provider: npm
  on:
    tags: true
